spring.application.name=api_cursos

#Banco Local
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/db_cursos
#spring.datasource.username=postgres
#spring.datasource.password=150699

#Banco Render
spring.datasource.url=jdbc:postgresql://dpg-d4a7223ipnbc739fdalg-a.oregon-postgres.render.com/apicursos_qynp
spring.datasource.username=apicursos
spring.datasource.password=5vlZky5sKr0oV7zkEhjndaAI7WUZtY8w

spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.minhacriptografia:"LuFoDa1029349ndklsndkso"
spring.sessao:30
